name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**' # run if this folder is modified

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
